config/routes.rb
Rails.application.routes.draw do
  root to: 'cocktails#index'
  resources :cocktails, only: [:index, :show, :create, :new] do
    resources :doses, only: [:index, :create, :new, :show]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_one_attached :photo
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient }
  validates :ingredient, presence: true, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  has_many :cocktails, through: :ingredients
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]

  def index
    @cocktails = Cocktail.all
    @cocktail = Cocktail.new
  end

  def show
    @dose = Dose.new
    @doses = Dose.all
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :body, :photo)
  end

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
    before_action :set_cocktail, only: [:destroy, :index]

  def index
    @doses = Dose.all
  end

  def show; end

  def new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render 'cocktails/show'
    end

    def destroy
      # @dose = dose.find(params[:id])
      @dose.destroy
      redirect_to cocktail_path(@dose.cocktail)
    end

end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

  def set_dose
    @dose = Dose.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for cocktail do |f| %>
  <%= f.input :name %>

  <%= f.input :photo, as: :file %>
  <%= f.submit 'Create cocktail', class: 'btn btn-success' %>
  <%= link_to 'Back to index', cocktails_path, class: 'btn btn-link' %>


<% end %>

app/views/cocktails/edit.html.erb
<h1>Cocktail edition</h1>

<%# Version 3 %>
<%= render 'form', cocktail: @cocktail %>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
<h1>New cocktail</h1>

<%# Version 3 %>
<%= render 'form', cocktail: @cocktail %>
 </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<h2><%= @cocktail.name %></h2>

<div class="text-center padded">
<%= cl_image_tag @cocktail.photo.key, height: 300, width: 400, crop: :fill %>

<% @cocktail.doses.each do |dose| %>

        <h4><%= dose.description %> <%= dose.ingredient.name %></h4>

      <% end %>
<%= render 'doses/index'%>
<%= render 'doses/new'%>
<%= link_to "return to list", cocktails_path, class: "btn btn-success" %>

</div>

app/views/doses/_index.html.erb
<div class = "d-flex justify-content-between align-items-end px-4 py-2">
<h1>Our Ingredients</h1>
</div>

<div class="shadow mb-5 bg-white rounded">
  <% @cocktail.doses.each do |dose| %>
    <div class="border-bottom py-2 px-3">
      <div class="d-flex justify-content-between align-items-center">
        <div>
          <%= dose.description%>
          <%= dose.ingredient.name %>
          <%= link_to 'delete', dose_path(dose), class: 'btn btn-outline-danger btn-sm', method: 'delete', data: { confirm: 'Are you sure? Really?' } %>


        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/doses/_new.html.erb
<h2>Create a dose</h2>
<%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "add an ingredient", class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>